spring:
  application:
    name: IceButler_Server

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??
    url: jdbc:mysql://43.201.148.149:3306/icebulter
    username: root # ??????
    password: 1111 #  # ??????
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 13.125.164.38
    password: tmdgkr0802!

# TODO: 배포 재설정 후 수정
#  profiles:
#    include: API-KEY

logging.level:
  org.hibernate.SQL: debug

aws:
  s3:
    region: ap-northeast-2
    bucket: ice-bulter-iamge-bucket
    profile: profile/
  sqs:
    queue:
      url: https://sqs.ap-northeast-2.amazonaws.com/637108728135/FoodData.fifo
      name: FoodData.fifo
    accesskey: AKIAZIVVDWFDXIOMYWYT
    secretkey: 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
    region:
      static: ap-northeast-2

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  admin-secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-expired-time: 1209600000
  refresh-expired-time: 63200000000
  auth-header: Authorization
  token-type: Bearer
  access-name: ACCESS-TOKEN
  refresh-name: REFRESH-TOKEN

server:
  recipe:
    url: https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/dev-ice-bulter-recipe

apple:
  production:
    url: https://buy.itunes.apple.com/verifyReceipt
  sandbox:
    url: https://sandbox.itunes.apple.com/verifyReceipt
